[production]
working_group= 'rd'
analysis     = 'rd_ap_2024'

[sample]
eventtype= '94000000'
polarity = ['magup', 'magdown']
datatype = 2024
version  = 'v1r1364'

[splitting]
groups   = 100

[hlt_lines]
lines_phys_ee_mva= [
    'Hlt2RD_BuToKpEE_MVA',
    'Hlt2RD_B0ToKpPimEE_MVA',
    'Hlt2RD_LbTopKEE_MVA',
    'Hlt2RD_BsToPhiEE_MVA']

lines_phys_mm_mva= [
    'Hlt2RD_BuToKpMuMu_MVA',
    'Hlt2RD_B0ToKpPimMuMu_MVA',
    'Hlt2RD_LbTopKMuMu_MVA',
    'Hlt2RD_BsToPhiMuMu_MVA']

lines_ss_ee_mva= [
    'Hlt2RD_BuToKpEE_SameSign_MVA',
    'Hlt2RD_B0ToKpPimEE_SameSign_MVA',
    'Hlt2RD_LbTopKEE_SameSign_MVA',
    'Hlt2RD_BsToPhiEE_SameSign_MVA']

lines_ss_mm_mva= [
    'Hlt2RD_BuToKpMuMu_SameSign_MVA',
    'Hlt2RD_B0ToKpPimMuMu_SameSign_MVA',
    'Hlt2RD_LbTopKMuMu_SameSign_MVA',
    'Hlt2RD_BsToPhiMuMu_SameSign_MVA']

lines_misid_mm_mva= [
    'Hlt2RD_BuToKpEE_MVA_misid',
    'Hlt2RD_B0ToKpPimEE_MVA_misid',
    'Hlt2RD_LbTopKEE_MVA_misid',
    'Hlt2RD_BsToPhiEE_MVA_misid']

lines_calib_mm_mva= [
    'Hlt2RD_BuToKpEE_MVA_cal',
    'Hlt2RD_B0ToKpPimEE_MVA_cal']

lines_phys_ee_cut= [
    'Hlt2RD_BuToKpEE',
    'Hlt2RD_B0ToKpKmEE',
    'Hlt2RD_LbToLEE_LL']

lines_calib_ee_cut= [
    'Hlt2RD_BuToKpJpsi_JpsiToEE',
    'Hlt2RD_BuToKpJpsi_JpsiToMuMu',
    'Hlt2RD_LbToPKJpsi_JpsiToEE']

lines_calib_mm_cut= [
    'Hlt2RD_BdToKstJpsi_KstToKpPim_JpsiToEE',
    'Hlt2RD_BdToKstJpsi_KstToKpPim_JpsiToMuMu',
    'Hlt2RD_LbToPKJpsi_JpsiToMuMu']

lines_phys_mm_cut= [
    'Hlt2RD_LbToLMuMu_LL']

[selection]
prescale=100
cuts    =[]

[saving]
max_events  =-1
compression =2
store_branch=false
