[project]
name        = 'data_checks'
version     = '0.0.1'
dependencies= ['tqdm', 'rx_scripts', 'apd', 'xrootd', 'matplotlib'] 

[project.optional-dependencies]
dev  = []

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
save_pfns            ='data_checks_scripts.save_pfns:main'
ntup_info            ='data_checks_scripts.ntup_info:main'
yield_vs_lumi        ='data_checks_scripts.yield_vs_lumi:main'
filter_ntuples       ='data_checks_scripts.filter_ntuples:main'
run3_download_ntuples='data_checks_scripts.run3_download_ntuples:main'

[tool.setuptools.package-data]
'data_checks_data' = ['*.json', '*.toml']

[tool.setuptools]
script-files=['src/data_checks_scripts/update_tarball', 'src/data_checks_scripts/update_config']

