[project]
name        = 'data_checks'
version     = '0.0.1'
dependencies= ['tqdm', 'rx_scripts', 'apd', 'xrootd'] 

[project.optional-dependencies]
dev  = []

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
save_pfns='data_checks_scripts.save_pfns:main'
filter_ntuples='data_checks_scripts.filter_ntuples:main'

[tool.setuptools.package-data]
'data_checks_data' = ['*.json', '*.toml']

