[project]
name        = 'data_checks'
version     = '0.0.1'
dependencies= ['tqdm', 'rx_scripts', 'apd'] 

[project.optional-dependencies]
dev  = []

[tools.setuptools.packages.find]
where=['src']

[project.scripts]
save_pfns='data_checks_scripts.save_pfns:main'

