[selection]
prescale=1

[selection.cuts]
none   = '(1)'
b_mass = 'B_M      > 5000 && B_M      < 5600'
j_mass = 'Jpsi_M   > 2900 && Jpsi_M   < 3300'
H1Ghost= 'H1_TRGHOSTPROB < 0.5'
H2Ghost= 'H2_TRGHOSTPROB < 0.5'
L1Ghost= 'L1_TRGHOSTPROB < 0.5'
L2Ghost= 'L2_TRGHOSTPROB < 0.5'

[define_vars]
maxlpt= 'TMath::Max(L1_PT, L2_PT)'
minlpt= 'TMath::Min(L1_PT, L2_PT)'

[plots]

[plots.B_M]
binning=[4800, 6000, 100]
yscale ='log'
labels =['$M(B_d)[MeV]$', '']

[plots.Jpsi_M]
binning=[2800, 3300, 100]
yscale ='linear'
labels =['$M(J/\psi)[MeV]$', '']

[plots.Kst_M]
binning=[700, 1200, 100]
yscale ='linear'
labels =['$M(K^(*0))[MeV]$', '']

[plots.B_const_mass_M]
binning=[4800, 5800, 100]
yscale ='linear'
labels =['$M_{DTF}(B_d)[MeV]$', '']

[plots.maxlpt]
binning=[   0, 2000, 100]
yscale ='log'
labels =['$\max p_T(\ell)[MeV]$', '']

[plots.minlpt]
binning=[   0, 2000, 100]
yscale ='log'
labels =['$\min p_T(\ell)[MeV]$', '']

[plots.H1_PT]
binning=[   0, 2000, 100]
yscale ='log'
labels =['$p_T(K^+)[MeV]$', '']

[plots.H2_PT]
binning=[   0, 2000, 100]
yscale ='log'
labels =['$p_T(\pi^-)[MeV]$', '']

[plots.H1_PROBNN_K]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob_{K}^{NN}(K^+)$', '']

[plots.H2_PROBNN_PI]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob_{\pi}^{NN}(K^+)$', '']

[plots.H1_TRGHOSTPROB]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob^{ghost}(K^+)$', '']

[plots.H2_TRGHOSTPROB]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob^{ghost}(\pi^-)$', '']

[plots.L1_TRGHOSTPROB]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob^{ghost}(\mu^+)$', '']

[plots.L2_TRGHOSTPROB]
binning=[   0,    1, 100]
yscale ='log'
labels =['$Prob^{ghost}(\mu^-)$', '']


[saving]
plt_dir='/home/acampove/Packages/RK/data_checks/plots/bukmm'

