[selection]
max_ran_entries=50_000

[selection.cuts]
KpGhost= 'H_TRGHOSTPROB  < 0.5'
L1Ghost= 'L1_TRGHOSTPROB < 0.5'
L2Ghost= 'L2_TRGHOSTPROB < 0.5'

[definitions]
xbrem  = 'L1_HASBREM + L2_HASBREM'
maxlpt = 'TMath::Max(L1_PT, L2_PT)'
minlpt = 'TMath::Min(L1_PT, L2_PT)'

[plots]

[plots.B_M]
binning   =[4500, 6000, 100]
yscale    ='linear'
labels    =['$M(B^+)[MeV]$', '']
normalized=true

[plots.Jpsi_M]
binning   =[2400, 3300, 100]
yscale    ='linear'
labels    =['$M(J/\psi)[MeV]$', '']
normalized=true

[plots.B_const_mass_M]
binning   =[4800, 5800, 100]
yscale    ='linear'
labels    =['$M_{DTF}(B^+)[MeV]$', '']
normalized=true

[plots.xbrem]
binning   =[   0,    3,   3]
yscale    ='linear'
labels    =['$n_{\gamma}$', '']
normalized=true

[plots.maxlpt]
binning   =[   0, 15000, 100]
yscale    ='log'
labels    =['$\max p_T(\ell, \ell)[MeV]$', '']
normalized=true

[plots.minlpt]
binning   =[   0, 10000, 100]
yscale    ='log'
labels    =['$\min p_T(\ell, \ell)[MeV]$', '']
normalized=true

[plots.H_PT]
binning   =[   0, 20000, 100]
yscale    ='log'
labels    =['$p_T(K^+)[MeV]$', '']
normalized=true

[plots.H_PID_E]
binning   =[  -5,    2, 100]
yscale    ='log'
labels    =['$PID_e(K^+)$', '']
normalized=true

[plots.L1_PIDe]
binning   =[  -5,    5, 100]
yscale    ='linear'
labels    =['$PID_e(L1)$', '']
normalized=true

[plots.L2_PIDe]
binning   =[  -5,    5, 100]
yscale    ='linear'
labels    =['$PID_e(L2)$', '']
normalized=true

[plots.H_PROBNN_K]
binning   =[   0,    1, 100]
yscale    ='log'
labels    =['$Prob_{K}^{NN}(K^+)$', '']
normalized=true

[plots.H_TRGHOSTPROB]
binning   =[   0,    1, 100]
yscale    ='log'
labels    =['$Prob^{ghost}(K^+)$', '']
normalized=true

[plots.L1_TRGHOSTPROB]
binning   =[   0,    1, 100]
yscale    ='log'
labels    =['$Prob^{ghost}(e^+)$', '']
normalized=true

[plots.L2_TRGHOSTPROB]
binning   =[   0,    1, 100]
yscale    ='log'
labels    =['$Prob^{ghost}(e^-)$', '']
normalized=true

[saving]
plt_dir='/publicfs/ucas/user/campoverde/Packages/RK/data_checks/plots/bukee'
