[production]
working_group= 'rd'
analysis     = 'btoxll_mva_2024'

[sample]
names        = [
    'data_24_magdown_turbo_24c1',
    'data_24_magdown_turbo_24c2',
    'data_24_magdown_turbo_24c3',
    'data_24_magup_turbo_24c1',
    'data_24_magup_turbo_24c2',
    'data_24_magup_turbo_24c3']

[drop_branches]
includes=[
    '_cone_indx_',
    '_DTF_PV_B_mass_const_',
    '_DTF_noPV_',
    'ChargedIso',
    'NeutralIso',
    'SMOG2',
    '_EE2KK_',
    '_EE2PiPi_',
    '_K2P_',
    '_K2Pi_',
    '_KP2PK_',
    '_P2K_',
    '_MuMu2KK_',
    '_MuMu2PiPi_',
    '_MuMuK2KKPi_',
    '_MuMuK2PiPiPi_',
    '_POS_COV_MATRIX_',
    '_MOM_POS_COV_MATRIX_',
    '_MOM_COV_MATRIX_',
    '_POSITION_STATEAT_',
    'CutBasedIncl',
    '_InclDet',
    '_RICH_THRESHOLD_',
    ]

starts_with=[
    'B_Hlt1',
	'Lz_Hlt1',
	'Lb_Hlt1',
	'Jpsi_Hlt1',
	'B_K2Pi_DTF_',
	'K_',
	'Hlt1Di',
	'Hlt1BGI',
	'B_DTF_PV_Jpsi_mass_const_M',
	'B_DTF_PV_Psi2S_mass_const_M']

[rename]
B_DTF_PV_Jpsi_mass_const_M  ='B_const_mass_M'
Lb_DTF_PV_Jpsi_mass_const_M ='B_const_mass_M'
B_DTF_PV_Psi2S_mass_const_M ='B_const_mass_psi2S_M'
Lb_DTF_PV_Psi2S_mass_const_M='B_const_mass_psi2S_M'
L1_PID_E                    ='L1_PIDe'
L2_PID_E                    ='L2_PIDe'
K_PID_E                     ='H_PIDe'
K_PROBNN_K                  ='H_ProbNNk'
K_TRGHOSTPROB               ='H_TRACK_GhostProb'
H1_PROBNN_K                 ='H1_ProbNNk'
H2_PROBNN_K                 ='H2_ProbNNk'
L1_TRGHOSTPROB              ='L1_TRACK_GhostProb'
L2_TRGHOSTPROB              ='L2_TRACK_GhostProb'
L1_PID_MU                   ='L1_PIDmu'
L2_PID_MU                   ='L2_PIDmu'
L1_ISMUON                   ='L1_isMuon'
L2_ISMUON                   ='L2_isMuon'

[hlt_lines]
lines_phys_ee_mva= [
    'Hlt2RD_BuToKpEE_MVA',
    'Hlt2RD_B0ToKpPimEE_MVA',
    'Hlt2RD_LbTopKEE_MVA',
    'Hlt2RD_BsToPhiEE_MVA']

lines_phys_mm_mva= [
    'Hlt2RD_BuToKpMuMu_MVA',
    'Hlt2RD_B0ToKpPimMuMu_MVA',
    'Hlt2RD_LbTopKMuMu_MVA',
    'Hlt2RD_BsToPhiMuMu_MVA']

lines_phys_ee_cut= [
    'Hlt2RD_BuToKpEE',
    'Hlt2RD_B0ToKpPimEE',
    'Hlt2RD_LbToLEE_LL']

lines_phys_mm_cut= [
    'Hlt2RD_BuToKpMuMu',
    'Hlt2RD_B0ToKpPimMuMu',
    'Hlt2RD_LbToLMuMu_LL']

[selection]
prescale=1
[selection.cuts]
[selection.cuts.any]
L1Ghost= 'L1_TRGHOSTPROB < 0.5'
L2Ghost= 'L2_TRGHOSTPROB < 0.5'

[selection.cuts.bukee]
b_mass = 'B_const_mass_M > 4500 && B_const_mass_M < 6000'
KpGhost= 'H_TRGHOSTPROB  < 0.5'

[selection.cuts.bukmm]
b_mass = 'B_const_mass_M > 5000 && B_const_mass_M < 5800'
KpGhost= 'H_TRGHOSTPROB  < 0.5'

[selection.cuts.bdkstee]
b_mass = 'B_const_mass_M > 4500 && B_const_mass_M < 6000'
k_mass = 'Kst_M    >  800 && Kst_M   < 1000'
H1Ghost= 'H1_TRGHOSTPROB < 0.5'
H2Ghost= 'H2_TRGHOSTPROB < 0.5'

[selection.cuts.bdkstmm]
b_mass = 'B_const_mass_M > 5000 && B_const_mass_M < 5800'
k_mass = 'Kst_M    >  800 && Kst_M   < 1000'
H1Ghost= 'H1_TRGHOSTPROB < 0.5'
H2Ghost= 'H2_TRGHOSTPROB < 0.5'

[selection.cuts.lbpkee]
b_mass = 'B_const_mass_M > 4500 && B_const_mass_M < 6000'

[selection.cuts.lbpkmm]
b_mass = 'B_const_mass_M > 5000 && B_const_mass_M < 5800'

[saving]
max_events  =-1
compression =2
store_branch=false
[saving.tree_name]
KEE= [
    'Hlt2RD_BuToKpEE_MVA',
    'Hlt2RD_B0ToKpPimEE_MVA',
    'Hlt2RD_LbTopKEE_MVA',
    'Hlt2RD_BsToPhiEE_MVA',
    'Hlt2RD_BuToKpEE',
    'Hlt2RD_B0ToKpPimEE',
    'Hlt2RD_LbToLEE_LL']

KMM= [
    'Hlt2RD_BuToKpMuMu_MVA',
    'Hlt2RD_B0ToKpPimMuMu_MVA',
    'Hlt2RD_LbTopKMuMu_MVA',
    'Hlt2RD_BsToPhiMuMu_MVA',
    'Hlt2RD_BuToKpMuMu',
    'Hlt2RD_B0ToKpPimMuMu',
    'Hlt2RD_LbToLMuMu_LL']

