[production]
working_group= 'rd'
analysis     = 'rd_ap_2024'

[sample]
version  = 'v1r1364'
name_rx  = '^mc_(bu|bd|bs|lb)_.*_turbo_.*tupling$' 



[drop_branches]
includes=[
    '_cone_indx_',
    '_DTF_PV_B_mass_const_',
    '_DTF_noPV_',
    'ChargedIso',
    'NeutralIso',
    'SMOG2',
    '_EE2KK_',
    '_EE2PiPi_',
    '_K2P_',
    '_K2Pi_',
    '_KP2PK_',
    '_P2K_',
    '_MuMu2KK_',
    '_MuMu2PiPi_',
    '_MuMuK2KKPi_',
    '_MuMuK2PiPiPi_',
    '_POS_COV_MATRIX_',
    '_MOM_POS_COV_MATRIX_',
    '_MOM_COV_MATRIX_',
    '_POSITION_STATEAT_',
    'CutBasedIncl',
    '_InclDet',
    '_RICH_THRESHOLD_',
    ]

starts_with=[
    'B_Hlt1',
    'Lz_Hlt1',
    'Lb_Hlt1',
    'Jpsi_Hlt1',
    'B_K2Pi_DTF_',
    'K_',
    'Hlt1Di',
    'Hlt1BGI',
    'B_DTF_PV_Jpsi_mass_const_M',
    'B_DTF_PV_Psi2S_mass_const_M',
    ]

[rename]
B_DTF_PV_Jpsi_mass_const_M  ='B_const_mass_M'
Lb_DTF_PV_Jpsi_mass_const_M ='B_const_mass_M'
B_DTF_PV_Psi2S_mass_const_M ='B_const_mass_psi2S_M'
Lb_DTF_PV_Psi2S_mass_const_M='B_const_mass_psi2S_M'
B_BPVFDCHI2                 ='B_FDCHI2_OWNPV'
L1_PID_E                    ='L1_PIDe'
L2_PID_E                    ='L2_PIDe'
K_PROBNN_K                  ='H_ProbNNk'
K_TRGHOSTPROB               ='H_TRACK_GhostProb'
H1_PROBNN_K                 ='H1_ProbNNk'
H2_PROBNN_K                 ='H2_ProbNNk'
L1_TRGHOSTPROB              ='L1_TRACK_GhostProb'
L2_TRGHOSTPROB              ='L2_TRACK_GhostProb'

[hlt_lines]
lines_phys_ee_mva= [
    'Hlt2RD_BuToKpEE_MVA',
    'Hlt2RD_B0ToKpPimEE_MVA',
    'Hlt2RD_LbTopKEE_MVA',
    'Hlt2RD_BsToPhiEE_MVA']

lines_phys_mm_mva= [
    'Hlt2RD_BuToKpMuMu_MVA',
    'Hlt2RD_B0ToKpPimMuMu_MVA',
    'Hlt2RD_LbTopKMuMu_MVA',
    'Hlt2RD_BsToPhiMuMu_MVA']

lines_phys_ee_cut= [
    'Hlt2RD_BuToKpEE',
    'Hlt2RD_B0ToKpPimEE',
    'Hlt2RD_LbToLEE_LL']

lines_phys_mm_cut= [
    'Hlt2RD_BuToKpMuMu',
    'Hlt2RD_B0ToKpPimMuMu',
    'Hlt2RD_LbToLMuMu_LL']

[selection]
prescale=1
[selection.cuts]
[selection.cuts.any]
BKGCAT ='BKGCAT == 0 || BKGCAT == 10 || BKGCAT == 50'
L1Ghost= 'L1_TRGHOSTPROB < 0.5'
L2Ghost= 'L2_TRGHOSTPROB < 0.5'

[saving]
max_events  =-1
compression =2
store_branch=false
[saving.tree_name]
KEE= [
    'Hlt2RD_BuToKpEE_MVA',
    'Hlt2RD_B0ToKpPimEE_MVA',
    'Hlt2RD_LbTopKEE_MVA',
    'Hlt2RD_BsToPhiEE_MVA',
    'Hlt2RD_BuToKpEE',
    'Hlt2RD_B0ToKpPimEE',
    'Hlt2RD_LbToLEE_LL']

KMM= [
    'Hlt2RD_BuToKpMuMu_MVA',
    'Hlt2RD_B0ToKpPimMuMu_MVA',
    'Hlt2RD_LbTopKMuMu_MVA',
    'Hlt2RD_BsToPhiMuMu_MVA',
    'Hlt2RD_BuToKpMuMu',
    'Hlt2RD_B0ToKpPimMuMu',
    'Hlt2RD_LbToLMuMu_LL']

